feat: create about us page
IT-Academy-Kyrgyzstan/cs2001-mark1 pull request #14
Opened 2020-12-04 18:07 UTC by rustam217

closes #13

2020-12-07 14:30 UTC, amankkg requested changes

2020-12-07 14:30 UTC, amankkg commented on Web/Views/Home/Index.cshtml
> +<head>
`head` тэг уже рендерится в `_Layout.cshtml` вьюшке (каркас страницы), надо убрать

2020-12-07 14:30 UTC, amankkg commented on Web/Views/Home/Index.cshtml
> +        h6{color:darkslateblue; font-family:'Trebuchet MS';}
надо такие стили вынести в отдельный класс в отдельном файле стилей, но как их потом подключать мы расскажем

2020-12-07 14:30 UTC, amankkg commented on Web/Views/Home/Index.cshtml
> +        h6{color:darkslateblue; font-family:'Trebuchet MS';}
пока пусть остается в виде тэга `style`

2020-12-07 14:30 UTC, amankkg commented on Web/Views/Home/Index.cshtml
> +<body>
`body` тэг тоже рендерится каркасом страницы

2020-12-07 14:30 UTC, amankkg commented on Web/Views/Home/Index.cshtml
> +    <h6>Company Name: Tech-Shop</h6>
1. не желательно прыгать через заголовки (`h1` и сразу `h6`)
2. данный текст лучше обернуть в `p` или `span`, т.к. это не заголовок, а сам контент

2020-12-10 19:39 UTC, rustam217 commented
closed #13

2020-12-11 13:36 UTC, amankkg requested changes

2020-12-11 13:36 UTC, amankkg commented on Web/Views/Home/AboutUs.cshtml
> +﻿
лишняя пустая строка

2020-12-11 13:36 UTC, amankkg commented on Web/Views/Home/AboutUs.cshtml
> +<p>Email: mark1shop@email.com</p>
для емейла есть спец. тэг `<a href="mailto:x@y.z"></a>`

2020-12-11 13:36 UTC, amankkg commented on Web/Web.csproj
> +    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.4" />
Что это за зависимость?

2020-12-11 13:57 UTC, amankkg approved these changes

2020-12-11 13:57 UTC, merged